"""empty message

Revision ID: 3319f8e99ff1
Revises: 7ff7cc394de3
Create Date: 2021-04-13 16:45:28.813737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3319f8e99ff1'
down_revision = '7ff7cc394de3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('perguntas', sa.Column('pergunta', sa.String(), nullable=False))
    op.add_column('temas', sa.Column('tema', sa.String(), nullable=False))
    op.drop_column('temas', 'nome')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temas', sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('temas', 'tema')
    op.drop_column('perguntas', 'pergunta')
    # ### end Alembic commands ###
