"""Add coloumn usuario_id in TemaModel

Revision ID: 4986c90cba28
Revises: b59fd090aadc
Create Date: 2021-04-16 17:23:07.279430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4986c90cba28'
down_revision = 'b59fd090aadc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temas', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'temas', 'usuarios', ['usuario_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('usuarios', 'usuario_pontos',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'usuario_pontos',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'temas', type_='foreignkey')
    op.drop_column('temas', 'usuario_id')
    # ### end Alembic commands ###
