"""Added column usuario_pontos in UserModel

Revision ID: b59fd090aadc
Revises: 3319f8e99ff1
Create Date: 2021-04-16 12:51:55.605282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b59fd090aadc'
down_revision = '3319f8e99ff1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('password_hash', sa.String(), nullable=False))
    op.add_column('usuarios', sa.Column('usuario_pontos', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'usuarios', ['nome'])
    op.create_unique_constraint(None, 'usuarios', ['email'])
    op.drop_column('usuarios', 'senha')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('senha', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'usuarios', type_='unique')
    op.drop_constraint(None, 'usuarios', type_='unique')
    op.drop_column('usuarios', 'usuario_pontos')
    op.drop_column('usuarios', 'password_hash')
    # ### end Alembic commands ###
