"""empty message

Revision ID: d4f710a0d4dc
Revises: b59fd090aadc
Create Date: 2021-04-16 16:21:31.435317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4f710a0d4dc'
down_revision = 'b59fd090aadc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'usuario_pontos',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'usuario_pontos',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
