"""Insert cascade effect in alternativa_model.py

Revision ID: dcaa6dfd771c
Revises: 4d8624d38c6c
Create Date: 2021-04-23 12:32:34.109488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcaa6dfd771c'
down_revision = '4d8624d38c6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('alternativas_pergunta_id_fkey', 'alternativas', type_='foreignkey')
    op.create_foreign_key(None, 'alternativas', 'perguntas', ['pergunta_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('temas', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('temas', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'alternativas', type_='foreignkey')
    op.create_foreign_key('alternativas_pergunta_id_fkey', 'alternativas', 'perguntas', ['pergunta_id'], ['id'])
    # ### end Alembic commands ###
